default:
	kotlinc dec_19.kt
	time kotlin Dec_19Kt < input

test:
	kotlinc dec_19.kt
	time kotlin Dec_19Kt < test2

test_three:
	kotlinc dec_19.kt
	time kotlin Dec_19Kt < test3
	time kotlin Dec_19Kt < test4

clean:
	-rm **.class META-INF/ -r
